### ISSUE TITLE
Would love to contribute

### ISSUE THREAD

**Issue by redbonzai** [dugajean/laravel-repositories#1]
What are some things that you would like assistance with ? 

Christian Dominguez

**Comment by dugajean** [comment]
Hi there, sorry for the late response. I have a planned to add some sort of caching in the package, but I'm not certain of the details yet. Maybe that's something that would interest you? Thanks for the interest!

**Comment by redbonzai** [comment]
caching like this repository ? 
https://github.com/andersao/l5-repository
Checkout their caching interface

**Comment by dugajean** [comment]
Yup something like that. Or maybe something among the lines of adding a `Cacheable` trait to the repository that you want to use caching. Then you opt-out of caching by simply not using the trait. What do you think?

**Comment by redbonzai** [comment]
That sounds like a plan.  I'll get started on that this weekend by installing the package, and begin the creation of the trait.

**Comment by dugajean** [comment]
I appreciate your help 🙇 😃

**Comment by redbonzai** [comment]
Created the CachableInterface.php within Dugajean\Repositories\Contracts.  I have the trait most of the way done;  this will rely also on a helpers file within Dugajean\Repositories\Helpers.  This is still WIP.

**Comment by Tjoosten** [comment]
@redbonzai Still making progress? 
@dugajean is it ok for u that i copy https://github.com/andersao/l5-repository/blob/master/src/Prettus/Repository/Traits/CacheableRepository.php to the repository with all the neede credits?
